# Generated by Django 5.0 on 2023-12-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='backend.entity'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='backend.function'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='backend.service'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='backend.entity_types'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponsibles', to='backend.employee'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponsibles', to='backend.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backend.phase'),
        ),
    ]
