# Generated by Django 5.0 on 2023-12-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_employee_entity_alter_employee_function_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity_Types',
            new_name='Entity_Type',
        ),
        migrations.AlterField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='backend.project'),
        ),
    ]
