# Generated by Django 5.0 on 2023-12-23 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_project_created_at_project_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
