# Generated by Django 5.0 on 2024-01-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_task_created_at_task_finished_task_finished_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='descrition',
            new_name='description',
        ),
    ]
