# Generated by Django 5.0 on 2024-01-20 07:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_descrition_entity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phases_nbr',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='backend.task'),
        ),
    ]
